# Generated by Django 5.1.4 on 2024-12-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('directivas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='directivas',
            name='nombre',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
