# Generated by Django 5.1.4 on 2024-12-15 21:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('directivas', '0002_directivas_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='directivas',
            old_name='año_fin',
            new_name='anio_fin',
        ),
        migrations.RenameField(
            model_name='directivas',
            old_name='año_inicio',
            new_name='anio_inicio',
        ),
    ]
